on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test code
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install required packages
        run : sudo apt-get install xorg-dev libgl1-mesa-dev libglfw3-dev libgles2-mesa-dev xkbcommon-x11
        if: runner.os == 'Linux'
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download
        run: go mod download
      - name: Vet
        run: go vet github.com/vron/gease/...
      - name: Test
        run: go test github.com/vron/gease/...
      - name: Test race
        run: go test -race github.com/vron/gease/...

  fmt:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fmt
        run: test -z $(go fmt github.com/vron/gease/...)
